server:
  port: 8001
spring:
  application:
    name: payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 95938
    url: jdbc:mysql://localhost:3307/photo
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
seata:
  registry: { type: nacos,
              nacos: {
                password: nacos,
                username: nacos,
                server-addr: 127.0.0.1:8848,
                namespace: "",
                group: SEATA_GROUP,
                application: seata-server
              }
  }
  tx-service-group: seata-wangxia
  service:
    vgroup-mapping:
      seata-wangxia: default

rocketmq:
  name-server: localhost:9876
  producer:
    group: pay


