spring:
  application:
    name: core
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 02e29b95-aa01-4c1e-aa7d-8b65956c8fa1
        extension-configs:
          - data-id: core-dev.yaml
            refresh: true
          - data-id: common-dev.yaml
            refresh: true
          - data-id: security-dev.yaml
            refresh: true
      discovery:
        namespace:
  config:
    import:
      - nacos:core-dev.yaml
      - nacos:common-dev.yaml
      - nacos:security-dev.yaml
logging:
  level:
    org:
      springframework:
        security: debug
